apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-srv-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-srv
  template:
    metadata:
      labels:
        app: posts-srv
    spec:
      containers:
        - name: posts-srv
          image: junaidofficialnow/posts-srv
          env:
            - name: KAFKA_URI
              value: pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv-srv
spec:
  selector:
    app: posts-srv
  ports:
    - name: posts-srv
      protocol: TCP
      port: 4001
      targetPort: 4001