apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-srv-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-srv
  template:
    metadata:
      labels:
        app: posts-srv
    spec:
      containers:
        - name: posts-srv
          image: junaidofficialnow/posts-srv
          envFrom:
          - configMapRef:
              name: shared-config-map
          - secretRef:
              name: mongodb-secrets
          - secretRef:
              name: kafka-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv-srv
spec:
  selector:
    app: posts-srv
  ports:
    - name: posts-srv
      protocol: TCP
      port: 4000
      targetPort: 4000